/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/book/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Book */
        get: operations["get_current_book_api_book_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin Book */
        post: operations["pin_book_api_book_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_book__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brief */
        get: operations["brief_api_brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hedge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hedge */
        post: operations["hedge_api_hedge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument */
        get: operations["instrument_api_instruments__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{symbol}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candles */
        get: operations["candles_api_instruments__symbol__candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply To Book Route */
        post: operations["apply_to_book_route_api_lab_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro */
        get: operations["macro_api_macro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{name}/fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fit */
        post: operations["fit_api_models__name__fit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{name}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_models__name__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options/book-greeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book Greeks */
        post: operations["book_greeks_api_options_book_greeks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options/{underlier}/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chain */
        get: operations["get_chain_api_options__underlier__chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/montecarlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Montecarlo */
        post: operations["montecarlo_api_risk_montecarlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk */
        get: operations["risk_api_risk__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/{symbol}/regression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regression */
        get: operations["regression_api_risk__symbol__regression_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotation */
        post: operations["rotation_api_rotation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Sync */
        post: operations["submit_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_sync__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whatif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Whatif */
        post: operations["whatif_api_whatif_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountOut */
        AccountOut: {
            /** Buying Power */
            buying_power: number | null;
            /** Gross Position Value */
            gross_position_value: number | null;
            /** Net Liquidation */
            net_liquidation: number | null;
            /** Total Cash Value */
            total_cash_value: number | null;
        };
        /**
         * AttributionOut
         * @description Requirement 4 — the product's identity number: daily book P&L
         *     decomposed into beta*bench_return*book_value (core) vs the residual
         *     (overlay), over `window_days` of the cached history. Pure math lives in
         *     exposure/attribution.py; this router only assembles the return series and
         *     estimates beta (quantmind.risk.returns.rolling_beta, the same estimator
         *     routers/risk.py and routers/hedge.py use).
         */
        AttributionOut: {
            /** Available */
            available: boolean;
            /** Beta */
            beta: number | null;
            /** Core Pnl */
            core_pnl: number | null;
            /** Core Share */
            core_share: number | null;
            /** N Obs */
            n_obs: number;
            /** Overlay Pnl */
            overlay_pnl: number | null;
            /** Overlay Share */
            overlay_share: number | null;
            /** Reason */
            reason: string | null;
            /** Series */
            series: components["schemas"]["AttributionPointOut"][];
            /** Total Pnl */
            total_pnl: number | null;
            /** Window Days */
            window_days: number;
        };
        /** AttributionPointOut */
        AttributionPointOut: {
            /** Core Pnl */
            core_pnl: number | null;
            /** Date */
            date: string;
            /** Overlay Pnl */
            overlay_pnl: number | null;
            /** Total Pnl */
            total_pnl: number | null;
        };
        /** AttributionRow */
        AttributionRow: {
            /** Annualized */
            annualized: number | null;
            /** Daily */
            daily: number | null;
            /** Name */
            name: string;
        };
        /** BenchmarkOut */
        BenchmarkOut: {
            /** Ann Vol */
            ann_vol: number | null;
            /** Es 975 */
            es_975: number | null;
            /** Symbol */
            symbol: string;
        };
        /** BetaEstimate */
        BetaEstimate: {
            /** Beta */
            beta: number | null;
            /** Ci High */
            ci_high: number | null;
            /** Ci Low */
            ci_low: number | null;
            /** Factor */
            factor: string;
            /** Se */
            se: number | null;
        };
        /** BetaPoint */
        BetaPoint: {
            /** Beta */
            beta: number | null;
            /** Date */
            date: string;
        };
        /** BookGreeksRequest */
        BookGreeksRequest: {
            /** Betas */
            betas?: {
                [key: string]: number;
            };
            /** Book Ref */
            book_ref?: string | null;
            /** Positions */
            positions?: components["schemas"]["PositionIn"][] | null;
        };
        /** BookGreeksResponse */
        BookGreeksResponse: {
            /** As Of */
            as_of: string | null;
            /** Risk Free Rate Note */
            risk_free_rate_note: string;
            stress_grid: components["schemas"]["StressGridOut"];
            /** Underlyings */
            underlyings: components["schemas"]["UnderlyingGreeksOut"][];
        };
        /** BookPinRequest */
        BookPinRequest: {
            /** Positions */
            positions?: components["schemas"]["PositionIn"][] | null;
        };
        /** BookPositionOut */
        BookPositionOut: {
            /** Con Id */
            con_id: number | null;
            /** Expiry */
            expiry?: string | null;
            /** Multiplier */
            multiplier: number;
            /** Qty */
            qty: number;
            /** Right */
            right?: ("C" | "P") | null;
            /** Sec Type */
            sec_type: string;
            /** Strike */
            strike?: number | null;
            /** Symbol */
            symbol: string;
        };
        /** BookSnapshotOut */
        BookSnapshotOut: {
            /** Base Currency */
            base_currency: string;
            /** Positions */
            positions: components["schemas"]["BookPositionOut"][];
            /** Snapshot Id */
            snapshot_id: string;
            /** Valuation Ts */
            valuation_ts: string;
        };
        /** BriefResponse */
        BriefResponse: {
            /** As Of */
            as_of: string | null;
            /** Benchmark Es */
            benchmark_es: number | null;
            correlation: components["schemas"]["Correlation"] | null;
            /** Tiles */
            tiles: components["schemas"]["Tile"][];
        };
        /** Candle */
        Candle: {
            /** Close */
            close: number | null;
            /** Date */
            date: string;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Open */
            open: number | null;
            /** Volume */
            volume: number | null;
        };
        /** CandlesResponse */
        CandlesResponse: {
            /** Candles */
            candles: components["schemas"]["Candle"][];
            /** Days */
            days: number;
            /** Symbol */
            symbol: string;
        };
        /** ChainResponse */
        ChainResponse: {
            /** As Of */
            as_of: string | null;
            /** Missing */
            missing: boolean;
            /** Quotes */
            quotes: components["schemas"]["OptionQuoteOut"][];
            /** Smile */
            smile: components["schemas"]["ExpirySmile"][];
            /** Spot */
            spot: number | null;
            /** Stale */
            stale: boolean;
            /** Underlier */
            underlier: string;
        };
        /** Correlation */
        Correlation: {
            /** Matrix */
            matrix: (number | null)[][];
            /** Symbols */
            symbols: string[];
        };
        /**
         * ExpiryBucketsOut
         * @description Requirement 5: option legs bucketed by days-to-expiry. Only legs that
         *     resolved to a priceable BookLeg (matching cached-chain IV) are bucketed —
         *     an unpriceable OPT position has no known expiry to bucket by.
         */
        ExpiryBucketsOut: {
            /** Later */
            later: components["schemas"]["ExpiryLegOut"][];
            /** Le 30D */
            le_30d: components["schemas"]["ExpiryLegOut"][];
            /** Le 7D */
            le_7d: components["schemas"]["ExpiryLegOut"][];
            /** Le 90D */
            le_90d: components["schemas"]["ExpiryLegOut"][];
        };
        /** ExpiryLegOut */
        ExpiryLegOut: {
            /** Days To Expiry */
            days_to_expiry: number;
            /** Expiry */
            expiry: string;
            /** Qty */
            qty: number;
            /** Right */
            right: string;
            /** Strike */
            strike: number;
            /** Symbol */
            symbol: string;
        };
        /** ExpirySmile */
        ExpirySmile: {
            /** Expiry */
            expiry: string;
            /** Points */
            points: components["schemas"]["SmilePoint"][];
        };
        /** ExposureRequest */
        ExposureRequest: {
            /** Factor Kind */
            factor_kind: string;
            /** Units */
            units: string;
            /** Value */
            value: number;
        };
        /**
         * FitLine
         * @description The single-factor (`factors[0]` alone) OLS line the scatter is drawn
         *     against. When more than one factor is requested this is DELIBERATELY not
         *     the same as that factor's `betas[]` entry below: `betas[]` is the
         *     multi-factor PARTIAL beta (holding the other factors fixed), while this
         *     is the simple two-variable slope — the gap between them is itself
         *     informative (it's what the other factors were absorbing).
         */
        FitLine: {
            /** Factor */
            factor: string;
            /** Intercept */
            intercept: number | null;
            /** R Squared */
            r_squared: number | null;
            /** Slope */
            slope: number | null;
            /** Slope Ci */
            slope_ci: [
                number | null,
                number | null
            ];
            /** Slope Se */
            slope_se: number | null;
        };
        /** FitRequest */
        FitRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Years
             * @default 5
             */
            years: number;
        };
        /** FitResponse */
        FitResponse: {
            /** Cis */
            cis: {
                [key: string]: [
                    number,
                    number
                ];
            };
            /** Diagnostics */
            diagnostics: {
                [key: string]: number;
            };
            /** Model Name */
            model_name: string;
            /** N Obs */
            n_obs: number;
            /** Params */
            params: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HedgeCandidateOut */
        HedgeCandidateOut: {
            /** Beta */
            beta: number | null;
            /** Corr Stability */
            corr_stability: number | null;
            /** Es After */
            es_after: number | null;
            /** Es Before */
            es_before: number | null;
            /** Hedge Notional */
            hedge_notional: number | null;
            /** Hedge Qty */
            hedge_qty: number | null;
            /** Protection */
            protection: number | null;
            /** Residual Beta */
            residual_beta: number | null;
            /** Symbol */
            symbol: string;
            /** Unusable */
            unusable: boolean;
        };
        /** HedgeRequest */
        HedgeRequest: {
            /** Book */
            book?: components["schemas"]["PositionIn"][] | null;
            /** Book Ref */
            book_ref?: string | null;
            /** Candidates */
            candidates?: string[] | null;
            objective: components["schemas"]["Objective"];
            /**
             * Years
             * @default 5
             */
            years: number;
        };
        /** HedgeResponse */
        HedgeResponse: {
            /** As Of */
            as_of: string | null;
            /** Benchmark */
            benchmark: string;
            /** Book Beta */
            book_beta: number | null;
            /** Book Value */
            book_value: number | null;
            /** Candidates */
            candidates: components["schemas"]["HedgeCandidateOut"][];
            /** Es Before */
            es_before: number | null;
            /** N Candidates Evaluated */
            n_candidates_evaluated: number;
            objective: components["schemas"]["Objective"];
        };
        /** Histogram */
        Histogram: {
            /** Bin Edges */
            bin_edges: number[];
            /** Counts */
            counts: number[];
        };
        /** InstrumentResponse */
        InstrumentResponse: {
            /** Ann Vol */
            ann_vol: number | null;
            /** As Of */
            as_of: string | null;
            /** Beta */
            beta: number | null;
            /** Beta Benchmark */
            beta_benchmark: string;
            /** Con Id */
            con_id: number;
            /** Currency */
            currency: string | null;
            /** Exchange */
            exchange: string | null;
            /** High 52W */
            high_52w: number | null;
            /** Industry */
            industry: string | null;
            /** Last Close */
            last_close: number | null;
            /** Long Name */
            long_name: string | null;
            /** Low 52W */
            low_52w: number | null;
            /** Pct From 52W High */
            pct_from_52w_high: number | null;
            /** Pct From 52W Low */
            pct_from_52w_low: number | null;
            /** Provider */
            provider: string | null;
            /** Region */
            region: string | null;
            /** Sec Type */
            sec_type: string | null;
            /** Symbol */
            symbol: string;
        };
        /** LabApplyRequest */
        LabApplyRequest: {
            exposure: components["schemas"]["ExposureRequest"];
            fit: components["schemas"]["FitResponse"];
            /**
             * Horizon
             * @default 126
             */
            horizon: number;
            /** Model Name */
            model_name: string;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
            /** X0 */
            x0?: number | null;
        };
        /** LabApplyResponse */
        LabApplyResponse: {
            /** Es */
            es: number | null;
            histogram: components["schemas"]["PnlHistogram"];
            /** Horizon */
            horizon: number;
            /** Mean */
            mean: number | null;
            /** N Nonfinite */
            n_nonfinite: number;
            /** N Paths */
            n_paths: number;
            /** P5 */
            p5: number | null;
            /** P50 */
            p50: number | null;
            /** P95 */
            p95: number | null;
        };
        /** MacroResponse */
        MacroResponse: {
            /** As Of */
            as_of: string | null;
            /** Factors */
            factors: components["schemas"]["RotationRow"][];
            /** Missing */
            missing: string[];
            net_liquidity: components["schemas"]["NetLiquidityBlock"] | null;
            /** Sectors */
            sectors: components["schemas"]["RotationRow"][];
            yields: components["schemas"]["YieldsBlock"] | null;
        };
        /** MonteCarloOut */
        MonteCarloOut: {
            histogram: components["schemas"]["Histogram"];
            /** N Nonfinite */
            n_nonfinite: number;
            /** P5 */
            p5: number | null;
            /** P50 */
            p50: number | null;
            /** P95 */
            p95: number | null;
        };
        /** MonteCarloParams */
        MonteCarloParams: {
            /**
             * Horizon
             * @default 126
             */
            horizon: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
        };
        /** MonteCarloRequest */
        MonteCarloRequest: {
            /**
             * Horizon
             * @default 252
             */
            horizon: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
            /** Symbol */
            symbol: string;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /** Es 975 */
            es_975: number | null;
            histogram: components["schemas"]["Histogram"];
            /** Horizon */
            horizon: number;
            /** N Nonfinite */
            n_nonfinite: number;
            /** N Paths */
            n_paths: number;
            /** P5 */
            p5: number | null;
            /** P50 */
            p50: number | null;
            /** P95 */
            p95: number | null;
            /** Symbol */
            symbol: string;
        };
        /** NetLiquidityBlock */
        NetLiquidityBlock: {
            /** Cadence Note */
            cadence_note: string;
            /** Latest Bn */
            latest_bn: number | null;
            /** Series */
            series: components["schemas"]["SeriesPoint"][];
        };
        /** NewsItemOut */
        NewsItemOut: {
            /** Headline */
            headline: string;
            /** Source */
            source: string;
            /** Symbol */
            symbol?: string | null;
            /** Time */
            time: string;
            /** Url */
            url?: string | null;
        };
        /** NewsResponse */
        NewsResponse: {
            /** As Of */
            as_of: string | null;
            /** Items */
            items: components["schemas"]["NewsItemOut"][];
            /** Note */
            note: string | null;
        };
        /** Objective */
        Objective: {
            /**
             * Kind
             * @default beta_target
             * @constant
             */
            kind: "beta_target";
            /** Value */
            value: number;
        };
        /** OptionQuoteOut */
        OptionQuoteOut: {
            /** Ask */
            ask: number | null;
            /** Bid */
            bid: number | null;
            /** Delta */
            delta: number | null;
            /** Expiry */
            expiry: string;
            /** Iv */
            iv: number | null;
            /** Multiplier */
            multiplier: number;
            /** Right */
            right: string;
            /** Strike */
            strike: number;
        };
        /**
         * OptionsSleeveOut
         * @description Requirement 3: per-underlying net Gamma/vega/theta + the spot x vol
         *     stress grid — renders only when option positions AND priceable chain
         *     data exist; the two honest-empty `reason`s are documented on the module
         *     docstring above.
         */
        OptionsSleeveOut: {
            /** Available */
            available: boolean;
            /** Reason */
            reason: string | null;
            stress_grid: components["schemas"]["StressGridOut"] | null;
            /** Underlyings */
            underlyings: components["schemas"]["SleeveUnderlyingOut"][];
        };
        /** OtherSideOut */
        OtherSideOut: {
            /** Corr */
            corr: number | null;
            /** Ret */
            ret: number | null;
            /** Score */
            score: number | null;
            /** Symbol */
            symbol: string;
        };
        /** PnlHistogram */
        PnlHistogram: {
            /** Bin Edges */
            bin_edges: number[];
            /** Counts */
            counts: number[];
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            account: components["schemas"]["AccountOut"] | null;
            /** Account Note */
            account_note: string | null;
            attribution: components["schemas"]["AttributionOut"];
            /** Base Currency */
            base_currency: string;
            expiry_buckets: components["schemas"]["ExpiryBucketsOut"];
            /** Exposure */
            exposure: components["schemas"]["UnderlyingExposureOut"][];
            options_sleeve: components["schemas"]["OptionsSleeveOut"];
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Snapshot Id */
            snapshot_id: string;
            totals: components["schemas"]["Totals"];
            /** Valuation Ts */
            valuation_ts: string;
        };
        /**
         * PositionIn
         * @description A book leg: qty != 0 shares/contracts of `symbol`. See module
         *     docstring for the option-leg fields' optionality/defaulting convention.
         */
        PositionIn: {
            /** Expiry */
            expiry?: string | null;
            /** Multiplier */
            multiplier?: number | null;
            /** Qty */
            qty: number;
            /** Right */
            right?: ("C" | "P") | null;
            /** Strike */
            strike?: number | null;
            /** Symbol */
            symbol: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Avg Cost */
            avg_cost?: number | null;
            /** Con Id */
            con_id: number;
            /** Last Close */
            last_close: number | null;
            /** Market Value */
            market_value: number | null;
            /** Multiplier */
            multiplier: number;
            /** Qty */
            qty: number;
            /** Sec Type */
            sec_type: string;
            /** Symbol */
            symbol: string;
            /** Unrealized Pnl */
            unrealized_pnl?: number | null;
            /** Weight */
            weight: number | null;
        };
        /** R2Step */
        R2Step: {
            /** Factor Added */
            factor_added: string;
            /** R Squared */
            r_squared: number | null;
        };
        /** RegressionResponse */
        RegressionResponse: {
            /** Alpha Annualized */
            alpha_annualized: number | null;
            /** Alpha Ci */
            alpha_ci: [
                number | null,
                number | null
            ];
            /** Alpha Daily */
            alpha_daily: number | null;
            /** Alpha Se */
            alpha_se: number | null;
            /** As Of */
            as_of: string | null;
            /** Attribution */
            attribution: components["schemas"]["AttributionRow"][];
            /** Betas */
            betas: components["schemas"]["BetaEstimate"][];
            /** Factors */
            factors: string[];
            fit_line: components["schemas"]["FitLine"];
            /** Hac Lags */
            hac_lags: number;
            /** Horizon Note */
            horizon_note: string;
            /** N Obs */
            n_obs: number;
            /** R Squared */
            r_squared: number | null;
            /** R Squared Progression */
            r_squared_progression: components["schemas"]["R2Step"][];
            /** Residuals */
            residuals: components["schemas"]["ResidualPoint"][];
            /** Scatter */
            scatter: components["schemas"]["ScatterPoint"][];
            /** Symbol */
            symbol: string;
            /** Variance Decomposition */
            variance_decomposition: components["schemas"]["ShareRow"][];
            /** Window */
            window: number | null;
            /** Years */
            years: number;
        };
        /** ResidualPoint */
        ResidualPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
        };
        /** RiskResponse */
        RiskResponse: {
            /** Alpha Annualized */
            alpha_annualized: number | null;
            /** Alpha Note */
            alpha_note: string;
            /** Ann Vol */
            ann_vol: number | null;
            /** As Of */
            as_of: string | null;
            /** Benchmark */
            benchmark: string;
            /** Beta Series */
            beta_series: components["schemas"]["BetaPoint"][];
            /** Es 975 */
            es_975: number | null;
            /** N Obs */
            n_obs: number;
            /** Symbol */
            symbol: string;
            /** Window */
            window: number;
            /** Years */
            years: number;
        };
        /** RotationRequest */
        RotationRequest: {
            /** Anchor */
            anchor?: string | null;
            /**
             * Corr Window
             * @default 60
             * @enum {integer}
             */
            corr_window: 20 | 60 | 120;
            /**
             * Return Days
             * @default 5
             */
            return_days: number;
            /** Symbols */
            symbols?: string[] | null;
            /**
             * Universe
             * @enum {string}
             */
            universe: "sectors" | "factors" | "world" | "custom";
        };
        /** RotationResponse */
        RotationResponse: {
            /** Anchor */
            anchor: string | null;
            /** As Of */
            as_of: string | null;
            /** Corr Window */
            corr_window: number;
            /** Matrix */
            matrix: (number | null)[][];
            /** Missing */
            missing: string[];
            /** Other Side */
            other_side: components["schemas"]["OtherSideOut"][] | null;
            /** Return Days */
            return_days: number;
            /** Returns */
            returns: components["schemas"]["SymbolReturnOut"][];
            /** Symbols */
            symbols: string[];
            /** Universe */
            universe: string;
        };
        /** RotationRow */
        RotationRow: {
            /** Ret 1D */
            ret_1d: number | null;
            /** Ret 1M */
            ret_1m: number | null;
            /** Ret 3M */
            ret_3m: number | null;
            /** Symbol */
            symbol: string;
        };
        /** ScatterPoint */
        ScatterPoint: {
            /** Asset */
            asset: number | null;
            /** Date */
            date: string;
            /** Factor */
            factor: number | null;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
        };
        /** ShareRow */
        ShareRow: {
            /** Name */
            name: string;
            /** Share */
            share: number | null;
        };
        /** SimulateRequest */
        SimulateRequest: {
            fit: components["schemas"]["FitResponse"];
            /**
             * Horizon
             * @default 126
             */
            horizon: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
            /** X0 */
            x0?: number | null;
        };
        /** SimulateResponse */
        SimulateResponse: {
            /** Bands */
            bands: {
                [key: string]: number[];
            };
            /** Horizon */
            horizon: number;
            /** N Paths */
            n_paths: number;
            /** Sample Paths */
            sample_paths: number[][];
        };
        /** SleeveUnderlyingOut */
        SleeveUnderlyingOut: {
            /** Gamma */
            gamma: number | null;
            /** Theta */
            theta: number | null;
            /** Underlier */
            underlier: string;
            /** Vega */
            vega: number | null;
        };
        /** SmilePoint */
        SmilePoint: {
            /** Iv */
            iv: number | null;
            /** Strike */
            strike: number;
        };
        /** StressGridOut */
        StressGridOut: {
            /** Pnl */
            pnl: (number | null)[][];
            /** Spot Shocks */
            spot_shocks: number[];
            /** Vol Shocks */
            vol_shocks: number[];
        };
        /** SymbolReturnOut */
        SymbolReturnOut: {
            /** Ret */
            ret: number | null;
            /** Symbol */
            symbol: string;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Error */
            error?: string | null;
            /** Result */
            result?: string | null;
            /** State */
            state: string;
        };
        /** SyncSubmitResponse */
        SyncSubmitResponse: {
            /** Job Id */
            job_id: string;
        };
        /** Tile */
        Tile: {
            /** Change 1D */
            change_1d: number;
            /** Last Close */
            last_close: number;
            /** Symbol */
            symbol: string;
        };
        /** Totals */
        Totals: {
            /** Market Value */
            market_value: number | null;
            /** N Positions */
            n_positions: number;
            /** Unrealized Pnl */
            unrealized_pnl?: number | null;
        };
        /**
         * UnderlyingExposureOut
         * @description Delta-adjusted exposure (Task B1 requirement 2 — "the number he
         *     manages to"): net delta (shares + option legs via book_greeks),
         *     dollar-delta, and SPY-equivalent notional (dollar-delta * per-underlier
         *     beta vs the app benchmark, estimated from cached bars).
         */
        UnderlyingExposureOut: {
            /** Beta */
            beta: number | null;
            /** Beta Note */
            beta_note: string | null;
            /** Dollar Delta */
            dollar_delta: number | null;
            /** Net Delta */
            net_delta: number | null;
            /** Spot */
            spot: number | null;
            /** Spy Equivalent Notional */
            spy_equivalent_notional: number | null;
            /** Underlier */
            underlier: string;
        };
        /** UnderlyingGreeksOut */
        UnderlyingGreeksOut: {
            /** Delta */
            delta: number | null;
            /** Dollar Delta */
            dollar_delta: number | null;
            /** Gamma */
            gamma: number | null;
            /** Spot */
            spot: number | null;
            /** Spy Equivalent Notional */
            spy_equivalent_notional: number | null;
            /** Theta */
            theta: number | null;
            /** Underlier */
            underlier: string;
            /** Vega */
            vega: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeightOut */
        WeightOut: {
            /** Market Value */
            market_value: number | null;
            /** Price */
            price: number | null;
            /** Qty */
            qty: number;
            /** Symbol */
            symbol: string;
            /** Weight */
            weight: number | null;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /** Book Ref */
            book_ref?: string | null;
            mc?: components["schemas"]["MonteCarloParams"];
            /** Positions */
            positions?: components["schemas"]["PositionIn"][] | null;
            /**
             * Years
             * @default 5
             */
            years: number;
        };
        /** WhatIfResponse */
        WhatIfResponse: {
            /** Ann Vol */
            ann_vol: number | null;
            /** As Of */
            as_of: string | null;
            benchmark: components["schemas"]["BenchmarkOut"];
            /** Beta */
            beta: number | null;
            /** Es 975 */
            es_975: number | null;
            mc: components["schemas"]["MonteCarloOut"];
            /** N Obs */
            n_obs: number;
            /** Weights */
            weights: components["schemas"]["WeightOut"][];
        };
        /** YieldsBlock */
        YieldsBlock: {
            /** Series */
            series: {
                [key: string]: components["schemas"]["SeriesPoint"][];
            };
            /** Spread 2S10S */
            spread_2s10s: number | null;
            /** Us10Y */
            us10y: number | null;
            /** Us2Y */
            us2y: number | null;
            /** Us3M */
            us3m: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_current_book_api_book_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookSnapshotOut"];
                };
            };
        };
    };
    pin_book_api_book_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookPinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_book__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brief_api_brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    hedge_api_hedge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HedgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HedgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instrument_api_instruments__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candles_api_instruments__symbol__candles_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_to_book_route_api_lab_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_api_macro_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroResponse"];
                };
            };
        };
    };
    models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fit_api_models__name__fit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_models__name__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_api_news_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
        };
    };
    book_greeks_api_options_book_greeks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookGreeksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookGreeksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chain_api_options__underlier__chain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                underlier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: {
                book_ref?: string | null;
                attribution_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    montecarlo_api_risk_montecarlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_api_risk__symbol__get: {
        parameters: {
            query?: {
                window?: number;
                years?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regression_api_risk__symbol__regression_get: {
        parameters: {
            query: {
                /** @description comma-separated factor names, e.g. SPY,MTUM,US10Y */
                factors: string;
                window?: number | null;
                years?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotation_api_rotation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSubmitResponse"];
                };
            };
        };
    };
    sync_status_api_sync__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatif_api_whatif_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
