/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brief */
        get: operations["brief_api_brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hedge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hedge */
        post: operations["hedge_api_hedge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply To Book Route */
        post: operations["apply_to_book_route_api_lab_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro */
        get: operations["macro_api_macro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{name}/fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fit */
        post: operations["fit_api_models__name__fit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{name}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_models__name__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/montecarlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Montecarlo */
        post: operations["montecarlo_api_risk_montecarlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk */
        get: operations["risk_api_risk__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Sync */
        post: operations["submit_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_sync__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whatif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Whatif */
        post: operations["whatif_api_whatif_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BenchmarkOut */
        BenchmarkOut: {
            /** Ann Vol */
            ann_vol: number | null;
            /** Es 975 */
            es_975: number | null;
            /** Symbol */
            symbol: string;
        };
        /** BetaPoint */
        BetaPoint: {
            /** Beta */
            beta: number | null;
            /** Date */
            date: string;
        };
        /** BookPositionIn */
        BookPositionIn: {
            /** Qty */
            qty: number;
            /** Symbol */
            symbol: string;
        };
        /** BriefResponse */
        BriefResponse: {
            /** As Of */
            as_of: string | null;
            /** Benchmark Es */
            benchmark_es: number | null;
            correlation: components["schemas"]["Correlation"] | null;
            /** Tiles */
            tiles: components["schemas"]["Tile"][];
        };
        /** Correlation */
        Correlation: {
            /** Matrix */
            matrix: (number | null)[][];
            /** Symbols */
            symbols: string[];
        };
        /** ExposureRequest */
        ExposureRequest: {
            /** Factor Kind */
            factor_kind: string;
            /** Units */
            units: string;
            /** Value */
            value: number;
        };
        /** FitRequest */
        FitRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Years
             * @default 5
             */
            years: number;
        };
        /** FitResponse */
        FitResponse: {
            /** Cis */
            cis: {
                [key: string]: [
                    number,
                    number
                ];
            };
            /** Diagnostics */
            diagnostics: {
                [key: string]: number;
            };
            /** Model Name */
            model_name: string;
            /** N Obs */
            n_obs: number;
            /** Params */
            params: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HedgeCandidateOut */
        HedgeCandidateOut: {
            /** Beta */
            beta: number | null;
            /** Coint Pvalue */
            coint_pvalue: number | null;
            /** Corr Stability */
            corr_stability: number | null;
            /** Es After */
            es_after: number | null;
            /** Es Before */
            es_before: number | null;
            /** Hedge Notional */
            hedge_notional: number | null;
            /** Hedge Qty */
            hedge_qty: number | null;
            /** Protection */
            protection: number | null;
            /** Residual Beta */
            residual_beta: number | null;
            /** Symbol */
            symbol: string;
            /** Unusable */
            unusable: boolean;
        };
        /** HedgeRequest */
        HedgeRequest: {
            /** Book */
            book: components["schemas"]["BookPositionIn"][];
            /** Candidates */
            candidates?: string[] | null;
            objective: components["schemas"]["Objective"];
            /**
             * Years
             * @default 5
             */
            years: number;
        };
        /** HedgeResponse */
        HedgeResponse: {
            /** As Of */
            as_of: string | null;
            /** Benchmark */
            benchmark: string;
            /** Book Beta */
            book_beta: number | null;
            /** Book Value */
            book_value: number | null;
            /** Candidates */
            candidates: components["schemas"]["HedgeCandidateOut"][];
            /** Es Before */
            es_before: number | null;
            /** N Candidates Evaluated */
            n_candidates_evaluated: number;
            objective: components["schemas"]["Objective"];
        };
        /** Histogram */
        Histogram: {
            /** Bin Edges */
            bin_edges: number[];
            /** Counts */
            counts: number[];
        };
        /** LabApplyRequest */
        LabApplyRequest: {
            exposure: components["schemas"]["ExposureRequest"];
            fit: components["schemas"]["FitResponse"];
            /**
             * Horizon
             * @default 126
             */
            horizon: number;
            /** Model Name */
            model_name: string;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
            /** X0 */
            x0?: number | null;
        };
        /** LabApplyResponse */
        LabApplyResponse: {
            /** Es */
            es: number | null;
            histogram: components["schemas"]["PnlHistogram"];
            /** Horizon */
            horizon: number;
            /** Mean */
            mean: number | null;
            /** N Nonfinite */
            n_nonfinite: number;
            /** N Paths */
            n_paths: number;
            /** P5 */
            p5: number | null;
            /** P50 */
            p50: number | null;
            /** P95 */
            p95: number | null;
        };
        /** MacroResponse */
        MacroResponse: {
            /** As Of */
            as_of: string | null;
            /** Factors */
            factors: components["schemas"]["RotationRow"][];
            /** Missing */
            missing: string[];
            net_liquidity: components["schemas"]["NetLiquidityBlock"] | null;
            /** Sectors */
            sectors: components["schemas"]["RotationRow"][];
            yields: components["schemas"]["YieldsBlock"] | null;
        };
        /** MonteCarloOut */
        MonteCarloOut: {
            histogram: components["schemas"]["Histogram"];
            /** N Nonfinite */
            n_nonfinite: number;
            /** P5 */
            p5: number | null;
            /** P50 */
            p50: number | null;
            /** P95 */
            p95: number | null;
        };
        /** MonteCarloParams */
        MonteCarloParams: {
            /**
             * Horizon
             * @default 126
             */
            horizon: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
        };
        /** MonteCarloRequest */
        MonteCarloRequest: {
            /**
             * Horizon
             * @default 252
             */
            horizon: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
            /** Symbol */
            symbol: string;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /** Es 975 */
            es_975: number | null;
            histogram: components["schemas"]["Histogram"];
            /** Horizon */
            horizon: number;
            /** N Nonfinite */
            n_nonfinite: number;
            /** N Paths */
            n_paths: number;
            /** P5 */
            p5: number | null;
            /** P50 */
            p50: number | null;
            /** P95 */
            p95: number | null;
            /** Symbol */
            symbol: string;
        };
        /** NetLiquidityBlock */
        NetLiquidityBlock: {
            /** Cadence Note */
            cadence_note: string;
            /** Latest Bn */
            latest_bn: number | null;
            /** Series */
            series: components["schemas"]["SeriesPoint"][];
        };
        /** Objective */
        Objective: {
            /**
             * Kind
             * @default beta_target
             * @constant
             */
            kind: "beta_target";
            /** Value */
            value: number;
        };
        /** PnlHistogram */
        PnlHistogram: {
            /** Bin Edges */
            bin_edges: number[];
            /** Counts */
            counts: number[];
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Base Currency */
            base_currency: string;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Snapshot Id */
            snapshot_id: string;
            totals: components["schemas"]["Totals"];
            /** Valuation Ts */
            valuation_ts: string;
        };
        /** PositionIn */
        PositionIn: {
            /** Qty */
            qty: number;
            /** Symbol */
            symbol: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Con Id */
            con_id: number;
            /** Last Close */
            last_close: number | null;
            /** Market Value */
            market_value: number | null;
            /** Multiplier */
            multiplier: number;
            /** Qty */
            qty: number;
            /** Sec Type */
            sec_type: string;
            /** Symbol */
            symbol: string;
            /** Weight */
            weight: number | null;
        };
        /** RiskResponse */
        RiskResponse: {
            /** Alpha Annualized */
            alpha_annualized: number | null;
            /** Alpha Note */
            alpha_note: string;
            /** Ann Vol */
            ann_vol: number | null;
            /** As Of */
            as_of: string | null;
            /** Benchmark */
            benchmark: string;
            /** Beta Series */
            beta_series: components["schemas"]["BetaPoint"][];
            /** Es 975 */
            es_975: number | null;
            /** N Obs */
            n_obs: number;
            /** Symbol */
            symbol: string;
            /** Window */
            window: number;
            /** Years */
            years: number;
        };
        /** RotationRow */
        RotationRow: {
            /** Ret 1D */
            ret_1d: number | null;
            /** Ret 1M */
            ret_1m: number | null;
            /** Ret 3M */
            ret_3m: number | null;
            /** Symbol */
            symbol: string;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
        };
        /** SimulateRequest */
        SimulateRequest: {
            fit: components["schemas"]["FitResponse"];
            /**
             * Horizon
             * @default 126
             */
            horizon: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Seed */
            seed?: number | null;
            /** X0 */
            x0?: number | null;
        };
        /** SimulateResponse */
        SimulateResponse: {
            /** Bands */
            bands: {
                [key: string]: number[];
            };
            /** Horizon */
            horizon: number;
            /** N Paths */
            n_paths: number;
            /** Sample Paths */
            sample_paths: number[][];
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Error */
            error?: string | null;
            /** Result */
            result?: string | null;
            /** State */
            state: string;
        };
        /** SyncSubmitResponse */
        SyncSubmitResponse: {
            /** Job Id */
            job_id: string;
        };
        /** Tile */
        Tile: {
            /** Change 1D */
            change_1d: number;
            /** Last Close */
            last_close: number;
            /** Symbol */
            symbol: string;
        };
        /** Totals */
        Totals: {
            /** Market Value */
            market_value: number | null;
            /** N Positions */
            n_positions: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeightOut */
        WeightOut: {
            /** Market Value */
            market_value: number;
            /** Price */
            price: number;
            /** Qty */
            qty: number;
            /** Symbol */
            symbol: string;
            /** Weight */
            weight: number;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            mc?: components["schemas"]["MonteCarloParams"];
            /** Positions */
            positions: components["schemas"]["PositionIn"][];
            /**
             * Years
             * @default 5
             */
            years: number;
        };
        /** WhatIfResponse */
        WhatIfResponse: {
            /** Ann Vol */
            ann_vol: number | null;
            /** As Of */
            as_of: string | null;
            benchmark: components["schemas"]["BenchmarkOut"];
            /** Beta */
            beta: number | null;
            /** Es 975 */
            es_975: number | null;
            mc: components["schemas"]["MonteCarloOut"];
            /** N Obs */
            n_obs: number;
            /** Weights */
            weights: components["schemas"]["WeightOut"][];
        };
        /** YieldsBlock */
        YieldsBlock: {
            /** Series */
            series: {
                [key: string]: components["schemas"]["SeriesPoint"][];
            };
            /** Spread 2S10S */
            spread_2s10s: number | null;
            /** Us10Y */
            us10y: number | null;
            /** Us2Y */
            us2y: number | null;
            /** Us3M */
            us3m: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    brief_api_brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    hedge_api_hedge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HedgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HedgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_to_book_route_api_lab_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_api_macro_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroResponse"];
                };
            };
        };
    };
    models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fit_api_models__name__fit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_models__name__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    montecarlo_api_risk_montecarlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_api_risk__symbol__get: {
        parameters: {
            query?: {
                window?: number;
                years?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSubmitResponse"];
                };
            };
        };
    };
    sync_status_api_sync__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatif_api_whatif_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
